### ISSUE TITLE
Does this work with vectors?

### ISSUE THREAD

**Issue by kvanbere** [achirkin/interprocess#4]
I have been poking around in the code for a few days to try and figure out whether this works for vectors or not.

My concern is that the buffer allocated for the MVar is the size of undefined, but what happens if you use a Storable ByteString that could have variable length? Or what happens if you use a Storable Boxed vector — will it realloc all the children values in the shared memory space also?

My use-case (to give you an idea) is sending a buffer of network packet bytes between processes. Thank you and happy holidays. @achirkin

**Comment by achirkin** [comment]
You're right, the MVar api is limited to `Storable` values at the moment, which by default don't support variable-size structures (because e.g. [Storable.sizeOf](https://hackage.haskell.org/package/base-4.14.1.0/docs/Foreign-Storable.html#v:sizeOf) isn't supposed to read values at runtime).
If you know the length of the Vector statically, you can create a newtype wrapper on top of it and implement an instance of Storable for it. Using the `Storable` also means all data is recursively serialized on every `putMVar` call, which may be not very efficient.
 
Alternatively, you can use the MVar's only for some fixed-length meta-information, but keep variable-length vector data in [Foreign.SharedPtr](https://hackage.haskell.org/package/interprocess-0.2.1.0/docs/Foreign-SharedPtr.html). This is a lower-level interface to share pointers to raw memory without any synchronization. Then implementing the serialization is completely up to you.

Hope this helps and happy holidays!

**Comment by kvanbere** [comment]
Thank you! I think the new type wrapper is the way to go, since each structure will probably only be ~100 bytes at most.
